### ISSUE TITLE
Cannot run under the Vite

### ISSUE THREAD

**Issue by sheepbox8646** [remarkablemark/texsvg#566]
When I try to use vite to start the server, it errs:

```txt
__vite-browser-external:url:3  Uncaught Error: Module "url" has been externalized for browser compatibility. Cannot access "url.pathToFileURL" in client code.  See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:url:3:11)
    at index.mjs:70936:9
```

And I saw the offical documentation, I discover:

![image](https://github.com/remarkablemark/texsvg/assets/78635021/49e05ea0-d649-46b9-ab09-1ad84f746a5f)

Could you mind let it become a ESMoudle?

**Comment by remarkablemark** [comment]
Thanks for opening the issue @sheepbox8646. Can you provide a reproducible example?

**Comment by sheepbox8646** [comment]
> Thanks for opening the issue @sheepbox8646. Can you provide a reproducible example?

https://github.com/dromara/newcar

you can see it in ./mods/mod-math/tex.ts

Vite seems do not support this way

**Comment by sheepbox8646** [comment]
And... you can find the example in ./examples

**Comment by remarkablemark** [comment]
Thanks! I'll try to find some time to take a look this weekend

**Comment by sheepbox8646** [comment]
> Thanks! I'll try to find some time to take a look this weekend

thanks！

**Comment by remarkablemark** [comment]
@sheepbox8646 I created a [StackBlitz](https://stackblitz.com/edit/texsvg-566) demo and it seems like this may not be possible since this library uses `mathjax` as a dependency and that's where the Vite error comes from.

**Comment by sheepbox8646** [comment]
ok，thanks for your trying, i'll find other ways

**Comment by sheepbox8646** [comment]
closed
